before_script:
  - psql -c 'create database love_notes_test;' -U postgres

language: ruby
rvm:
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
  - bundle exec rspec spec